version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    restart: 'no'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data #docker-down not working then to remove data partition
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test"
    ports:
        - "8080:80"
    depends_on:
        - postgres